Repository pre-onboarding-team-c/02-C-Payhere, pull requests merged in 2022-07, with the labels that each got.

#3 기초 세팅
  .gitignore
  index.js
  package-lock.json
  package.json
  src/app/controllers/index.js
  src/app/routers/index.js
  src/app/services/index.js
  src/db/index.js
Labels: 세팅

#7 feature/6 - feat : 프로젝트 기본 셋팅
  index.js
  package-lock.json
  package.json
  src/app/index.js
  src/app/routers/index.js
  src/app/routes/index.js
Labels: 세팅

#8 기초 DB 모델링
  package-lock.json
  package.json
  src/app/index.js
  src/app/routes/index.js
  src/db/config/config.json
  src/db/index.js
  src/db/models/AccountBook.js
  src/db/models/User.js
  src/db/models/index.js
  src/db/seeders/20220704063731-userData.js
  src/db/seeders/20220704063739-accountBookData.js
Labels: 기능 구현, 세팅

#13 가계부 CRUD 기본 세팅 및 AccountBook Model 수정
  src/app/controllers/accountBook.controller.js
  src/app/controllers/index.js
  src/app/routes/accountBook.router.js
  src/app/routes/index.js
  src/app/services/accountBook.service.js
  src/app/services/index.js
  src/db/models/AccountBook.js
  src/db/seeders/20220704063739-accountBookData.js
Labels: 기능 구현, 세팅

#14 feature/10 style : 함수 명칭 수정
  src/app/controllers/user.js
  src/app/routes/user.js
  src/app/services/user.js
Labels: 수정

#15 feature/12 - feat : 로그인
  src/app/controllers/user.js
  src/app/routes/user.js
  src/app/services/user.js
Labels: 기능 구현

#16 Feature/9 - status code, 응답 결정
  package-lock.json
  src/app/controllers/accountBook.controller.js
  src/app/index.js
  src/app/services/accountBook.service.js
  src/db/models/AccountBook.js
  src/db/models/User.js
Labels: 기능 구현

#25 Chore : Docker 세팅
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
  package.json
  src/app/services/accountBook.service.js
  src/db/config/config.js
  src/db/config/config.json
  src/db/models/AccountBook.js
  src/db/models/index.js
Labels: 세팅

#23 #22 - feat : 토큰 접근 제한 미들웨어, 재발급
  src/app/controllers/user.js
  src/app/middlewares/tokenMiddleware.js
  src/app/routes/user.js
  src/app/services/user.js
Labels: 기능 구현

#28 AccountBook 전체적인 리팩토링
  .prettierrc.js
  package-lock.json
  package.json
  src/app/controllers/accountBook.controller.js
  src/app/dto/accountBook.dto.js
  src/app/dto/index.js
  src/app/middlewares/index.js
  src/app/middlewares/validators/accountBook.validator.js
  src/app/middlewares/validators/index.js
  src/app/routes/accountBook.router.js
  src/app/services/accountBook.service.js
  src/db/models/AccountBook.js
  src/db/models/User.js
  src/db/seeders/20220704063739-accountBookData.js
Labels: 기능 구현, 수정

#29 refactor : 에러 핸들링
  src/app/controllers/user.js
  src/app/index.js
  src/app/middlewares/tokenMiddleware.js
  src/app/services/user.js
Labels: 수정

#31 Style : 명명 수정
  src/app/dto/index.js
  src/app/middlewares/validators/accountBook.validator.js
  src/app/schemas/accountBook.schema.js
  src/app/schemas/index.js
Labels: 수정

#32 Dto -> Schema 명명 수정
  src/app/dto/index.js
  src/app/middlewares/validators/accountBook.validator.js
  src/app/schemas/accountBook.schema.js
  src/app/schemas/index.js
Labels: 수정

#33 Refactor : 응답 수정
  src/app/controllers/accountBook.controller.js
Labels: 수정

#35 feat : Refresh Token 구현
  src/app/controllers/auth.controller.js
  src/app/controllers/index.js
  src/app/controllers/user.js
  src/app/middlewares/index.js
  src/app/middlewares/tokenMiddleware.js
  src/app/routes/auth.js
  src/app/routes/index.js
  src/app/routes/user.js
  src/app/services/auth.service.js
  src/app/services/index.js
  src/app/services/user.js
  src/app/utils/jwtToken.js
  src/db/models/User.js
Labels: 기능 구현

#37 Feat : AccountBook Schema, Validator 단위테스트 작성
  package-lock.json
  package.json
  src/app/controllers/accountBook.controller.js
  src/app/middlewares/validators/accountBook.validator.js
  src/app/middlewares/validators/accountBook.validator.test.js
  src/app/schemas/accountBook.schemas.test.js
Labels: 기능 구현

#38 Style : 파일명 수정
  src/app/controllers/index.js
  src/app/controllers/user.controller.js
  src/app/routes/auth.router.js
  src/app/routes/index.js
  src/app/routes/user.router.js
  src/app/services/index.js
  src/app/services/user.service.js
Labels: 수정

#41 User 타입 검증 미들웨어 구현
  src/app/middlewares/validators/index.js
  src/app/middlewares/validators/user.validator.js
  src/app/routes/accountBook.router.js
  src/app/routes/index.js
  src/app/schemas/index.js
  src/app/schemas/user.schema.js
Labels: 기능 구현

#42 Style : 오타 수정
  src/app/routes/index.js
Labels: 수정

#43 test : 토큰 미들웨어
  src/app/middlewares/tokenMiddleware.test.js
Labels: 기능 구현

#45 Refactor : 응답 코드, 결과, 헤더 수정
  src/app/controllers/accountBook.controller.js
  src/app/services/accountBook.service.js
  src/db/models/AccountBook.js
  src/db/models/User.js
Labels: 수정

#46 Refactor : Dockerfile 수정
  Dockerfile
Labels: 수정
